version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm run html
      - ls

artifacts:
  type: zip
  files:
    - package.json
    - package-lock.json
    - 'build/**/*'
    - 'static/**/*'
  discard-paths: no